var appConstants = {
    LOAD_PORTFOLIO: 'LOAD_PORTFOLIO',
    SAVE_PORTFOLIO: 'SAVE_PORTFOLIO',
    CREATE_COMPONENT: 'CREATE_COMPONENT',
    UPDATE_COMPONENT: 'UPDATE_COMPONENT',
    REMOVE_COMPONENT: 'REMOVE_COMPONENT'
};

module.exports = appConstants;